class Devtribunal < Formula
  desc "MCP server where each tool is a specialist code review agent"
  homepage "https://github.com/christophergutierrez/devtribunal"
  version "0.5.0"
  license "MIT"

  # Placeholder — real checksums are generated by CI on release
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/christophergutierrez/devtribunal/releases/download/v0.5.0/devtribunal-aarch64-apple-darwin.tar.gz"
      sha256 "placeholder"
    elsif Hardware::CPU.intel?
      url "https://github.com/christophergutierrez/devtribunal/releases/download/v0.5.0/devtribunal-x86_64-apple-darwin.tar.gz"
      sha256 "placeholder"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/christophergutierrez/devtribunal/releases/download/v0.5.0/devtribunal-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "placeholder"
    elsif Hardware::CPU.intel?
      url "https://github.com/christophergutierrez/devtribunal/releases/download/v0.5.0/devtribunal-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "placeholder"
    end
  end

  def install
    bin.install "devtribunal"
  end

  test do
    system bin/"devtribunal", "--version"
  end
end
